version: '3'

services:
  app: 
    container_name: garage_sale
    restart: always
    build: .
    links: 
      - redis
    expose:
      -  "8000"
    ports:
      -  "8000:8000"

  redis: 
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
   
    
  

